// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	bookManager "go-framework/service/book/api/internal/handler/bookManager"
	bookUse "go-framework/service/book/api/internal/handler/bookUse"
	health "go-framework/service/book/api/internal/handler/health"
	"go-framework/service/book/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Example},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/book/search",
					Handler: bookManager.SearchHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Example},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/book/rent",
					Handler: bookUse.RentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/book/back",
					Handler: bookUse.BackHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/book/ping",
				Handler: health.HealthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
